---

- pip:
    name:
      - boto
      - botocore
      - boto3

- name: Create {{ zookeeper_service_group }} system group
  group:
    name: "{{ zookeeper_service_group }}"
    state: present
    system: yes

- name: Create {{ zookeeper_service_user }} system user
  user:
    name: "{{ zookeeper_service_user }}"
    shell: /bin/bash
    groups: "{{ zookeeper_service_group }}"
    system: yes

- name: Create {{ zookeeper_install_directory }} persistent data directory
  file:
    path: "{{ zookeeper_install_directory }}"
    state: directory
    owner: "{{ zookeeper_service_user }}"
    group: "{{ zookeeper_service_group }}"
    mode: 0755

- name: Create temporary directory
  tempfile:
    state: directory
  register: temp_dir

- name: Download ZooKeeper binary package
  aws_s3:
    bucket: "{{ resource_bucket_name }}"
    object: "{{ resource_bucket_object_prefix }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    dest: "{{ temp_dir.path }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    mode: get

- name: Extract ZooKeeper binary package
  unarchive:
    remote_src: yes
    src: "{{ temp_dir.path }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    dest: "{{ temp_dir.path }}"

- name: Create ZooKeeper installation directory
  file:
    path: "{{ zookeeper_install_directory }}"
    state: directory
    owner: "{{ zookeeper_service_user }}"
    group: "{{ zookeeper_service_group }}"
    mode: 0755

- name: Install ZooKeeper
  copy:
    src: "{{ temp_dir.path }}/apache-zookeeper-{{ zookeeper_version }}-bin"
    dest: "{{ zookeeper_install_directory }}"
    owner: "{{ zookeeper_service_user }}"
    group: "{{ zookeeper_service_group }}"
    remote_src: yes
    mode: 0755

- name: Remove temporary directory
  file:
    path: temp_dir.path
    state: absent
