---

- name: Determine whether selinux is enforcing
  command: getenforce
  register: getenforce
  changed_when: false

- name: Set fact - selinux_enforcing
  set_fact:
    selinux_enforcing: "{{ (getenforce.stdout == 'Enforcing') | ternary(True, False) }}"

- name: Put SELinux in permissive mode during installation
  selinux:
    policy: targeted
    state: permissive
  when: selinux_enforcing

- name: Set system timezone to {{ zookeeper_timezone }}
  timezone:
    name: "{{ zookeeper_timezone }}"

- import_tasks: install_jdk.yml

- import_tasks: install_zookeeper.yml

- name: Put SELinux back in enforcing mode
  selinux:
    policy: targeted
    state: enforcing
  when: selinux_enforcing
