---

roles:
  - src: https://github.com/companieshouse/ansible-role-aws-nvme-device-files
    name: aws-nvme-device-files
    version: 1.1.0

  - src: https://github.com/companieshouse/ansible-role-mounted-volume
    name: mounted-volume
    version: 1.0.5

  - src: https://github.com/companieshouse/ansible-role-logrotate
    name: logrotate
    version: 1.6.1
